version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: ./ci-cd/nginx.Dockerfile
    ports:
      - "80:80"


  frontend:
    build:
      context: .
      dockerfile: ./ci-cd/frontend.Dockerfile
    ports:
      - "81:80"

  backend:
    env_file:
      - ./env/.env.backend
    build:
      context: .
      dockerfile: ./ci-cd/backend.Dockerfile
    ports:
      - "8000:8000"
